### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by kurupted** [vamsi3/screen-translator#1]
Does this work with the latest version of PapaGo? I came across your app just now, installed PapaGo, added the quick tile, etc, but when I click nothing happens. After a few tries I get the system popup saying the app keeps crashing.

Pixel 6 Pro

**Comment by vamsi3** [comment]
Hi. Thanks for checking out the repository. There were a few updates to this source code and the `apk` that I have been using in my daily life that didn't get updated upstream by me.

Unfortunately, I just realized I lost the updated source code due to a recent event. I am only left with the `apk` I use. For **your** security reasons, I will not share the `apk` directly here without the source, especially considering this app relies on accessibility features.

Now that I know there is an interest in this app, I'll rewrite it to update the app within the next week 😄 You can expect an update here once I'm done.

**Comment by kurupted** [comment]
Great, thanks.

The APK probably couldn't be a threat if you wanted it to, if it has accessibility permission but no network permissions, but looking forward to the updated release :)

**Comment by vamsi3** [comment]
Hi @kurupted. I've been busy for a while, so sorry to keep you waiting. I have updated the code and the corresponding `v0.0.1` APK binary. Can you try that out and see how it works for you?

**Comment by kurupted** [comment]
Thanks man. I had forgotten about this, coincidentally remembering this morning. It's working great now. Just had to find the "Allow restricted settings" thing so I could enable accessibility for it.

btw what does the notification swipe setting control?

**Comment by vamsi3** [comment]
For some context, if you look at the video, when the quick tile is pressed,

1. The app first 'simulates' a swipe-up to remove the notification panel from the screen view.
2. Then we take a screenshot, send it to Papago for translation.

So, the notification swipe setting controls whether or not you actually want this swipe up to happen (very likely you should keep it enabled). It also allows you to set how fast this swipe up should be simulated, this is because each phone has it's own animation speeds. So, adjust it according to your phone, so that screenshot happens after the notification panel is out of view. You can start from large value (like 1000 ms) and decrease the value from there.

**Comment by vamsi3** [comment]
It makes me ask now, what is your use-case for this app?

I'd be happy to know how do you use it so that I can improve the app further. (maybe integrate to Google Translate if possible _etc_).

**Comment by kurupted** [comment]
I'm living in Taiwan, so I'm constantly needing to translate things like UberEats menus or apps that don't have an English option.

Pleco works great for single bits of text, as you can copy/paste to Google Translate, but impractical for multiple separate strings.

Tap To Translate works but has annoying ads, and often makes a mess of the UI after translation.

Papago isn't quite as good as Google it seems, but works well enough. For Chinese, Deepl.com is usually best, but 🤷‍♂️

**Comment by vamsi3** [comment]
That's interesting. I've been to Taiwan last year, and I can see how you can find this useful. Papago works best for Korean <-> English, which is why I made this app for myself.

I'll keep in mind about DeepL, and look into it when I have more free time for this.

Closing the issue for now ~

**Comment by vamsi3** [comment]
@kurupted I have released a new version `v0.0.2` which has support for choosing your translate app of choice among Google Lens / NAVER Papago / DeepL Translate. Do check it out and let me know how it works~

**Comment by kurupted** [comment]
Ah that's great. Yeah it's working fine :)

Just wish Lens would jump straight to Translate as it defaults to Search. Probably nothing you can do about that.

Fyi, the app crashes instead of sending you to the Accessibility settings if you've done the "Allow restricted settings" but not yet enabled it. Maybe it's just Pixel phones but it's weird how you can't enable it til you Allow it, and you can't allow it til you've tried once to enable it. But yeah in between doing those two it will crash.

Thanks!
