### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by Mohadm58** [vamsi3/screen-translator#4]
When the phone is in Arabic, the application does not work. It also stops working because

**Comment by vamsi3** [comment]
Hi @Mohadm58!

I'll first consolidate all issues you have opened to put everything together at one place.

---

It doesn't work 😔 #5 

https://user-images.githubusercontent.com/68702788/229547691-d45ba828-29da-4c2e-a31b-585014ee462f.mp4

Google #6 

You can add better google. Install google lens Because Google search uses Google lens, I hope you understand 
![IMG_20230403_202931](https://user-images.githubusercontent.com/68702788/229608807-03a92aac-3370-48a2-aa91-eee63a60d1eb.jpg)

Watch the video #8
